In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from tensorflow import keras

In [2]:
df_train = pd.read_csv('DiseaseTraining.csv')
df_test = pd.read_csv('DiseaseTesting.csv')

In [3]:
df_train.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   
1       0           0             0        0                 0  ...         0   
2       0           0             0        0                 0  ...         0   
3       0           0             0        0                 0  ...         0   
4       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   
1             0                    0                     0   
2             0                    0                     0   
3             0                    0                     0   
4             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   
1                   0        0                     0                  0   
2                   0        0                     0                  0   
3                   0        0                     0                  0   
4                   0        0                     0                  0   

          prognosis  Unnamed: 133  
0  Fungal infection           NaN  
1  Fungal infection           NaN  
2  Fungal infection           NaN  
3  Fungal infection           NaN  
4  Fungal infection           NaN  

[5 rows x 134 columns]

In [4]:
df_train.drop(columns='Unnamed: 133', inplace=True)
df_train.head(3)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  

[3 rows x 133 columns]

In [5]:
df_test.head(3)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0           Allergy  
2                  0              GERD  

[3 rows x 133 columns]

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [7]:
df_train.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [8]:
df_test.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [10]:
df_train['prognosis'].value_counts()

Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Allergy      

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
df_train['prognosis'] = le.fit_transform(df_train['prognosis'])
df_train.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0         15  
1                  0         15  
2                  0         15  
3                  0         15  
4                  0         15  

[5 rows x 133 columns]

In [13]:
df_train['prognosis'].max()

40

In [14]:
df_test['prognosis'] = le.transform(df_test['prognosis'])
df_test.head(3)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0         15  
1                  0          4  
2                  0         16  

[3 rows x 133 columns]

In [15]:
le.classes_

array(['(vertigo) Paroymsal  Positional Vertigo', 'AIDS', 'Acne',
       'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma',
       'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis',
       'Common Cold', 'Dengue', 'Diabetes ',
       'Dimorphic hemmorhoids(piles)', 'Drug Reaction',
       'Fungal infection', 'GERD', 'Gastroenteritis', 'Heart attack',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia',
       'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine',
       'Osteoarthristis', 'Paralysis (brain hemorrhage)',
       'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
       'Typhoid', 'Urinary tract infection', 'Varicose veins',
       'hepatitis A'], dtype=object)

In [16]:
x_train = df_train.drop(columns='prognosis')
y_train = df_train['prognosis'] 

In [17]:
x_train.head(2)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   

   pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                   0           0         0             0   
1                   0           0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   

   red_sore_around_nose  yellow_crust_ooze  
0                     0                  0  
1                     0                  0  

[2 rows x 132 columns]

In [19]:
y_train.head(2)

0    15
1    15
Name: prognosis, dtype: int64

In [20]:
x_test = df_test.drop(columns='prognosis')
y_test = df_test['prognosis']

In [21]:
print(y_train[:1])
y_train = keras.utils.to_categorical(y_train, num_classes=41)
print(y_train[:1])

0    15
Name: prognosis, dtype: int64
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
print(y_train[:2])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [23]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [24]:
x_train.shape

(4920, 132)

In [25]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(x_train.shape[-1],)))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(units=41, activation='softmax'))

2023-04-13 05:13:15.469872: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-13 05:13:15.470530: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1


In [26]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                4256      
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 32)                1056      
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_3 (Dense)             (None, 41)                1353      
                                                                 
Total params: 7,721
Trainable params: 7,721
Non-trainabl

In [28]:
model.fit(x_train, y_train, batch_size=1000, epochs=50, verbose=2)

Epoch 1/50
5/5 - 0s - loss: 0.3028 - accuracy: 0.9179 - 57ms/epoch - 11ms/step
Epoch 2/50
5/5 - 0s - loss: 0.2970 - accuracy: 0.9173 - 50ms/epoch - 10ms/step
Epoch 3/50
5/5 - 0s - loss: 0.2871 - accuracy: 0.9203 - 48ms/epoch - 10ms/step
Epoch 4/50
5/5 - 0s - loss: 0.2528 - accuracy: 0.9307 - 48ms/epoch - 10ms/step
Epoch 5/50
5/5 - 0s - loss: 0.2506 - accuracy: 0.9323 - 48ms/epoch - 10ms/step
Epoch 6/50
5/5 - 0s - loss: 0.2486 - accuracy: 0.9374 - 48ms/epoch - 10ms/step
Epoch 7/50
5/5 - 0s - loss: 0.2394 - accuracy: 0.9362 - 49ms/epoch - 10ms/step
Epoch 8/50
5/5 - 0s - loss: 0.2393 - accuracy: 0.9337 - 48ms/epoch - 10ms/step
Epoch 9/50
5/5 - 0s - loss: 0.2414 - accuracy: 0.9313 - 49ms/epoch - 10ms/step
Epoch 10/50
5/5 - 0s - loss: 0.2198 - accuracy: 0.9404 - 49ms/epoch - 10ms/step
Epoch 11/50
5/5 - 0s - loss: 0.2359 - accuracy: 0.9372 - 49ms/epoch - 10ms/step
Epoch 12/50
5/5 - 0s - loss: 0.2186 - accuracy: 0.9396 - 48ms/epoch - 10ms/step
Epoch 13/50
5/5 - 0s - loss: 0.2080 - accuracy: 0

In [29]:
prediction = model.predict(x_test)
print(prediction[:1])

2/2 [==============================] - 0s 20ms/step
[[6.96155382e-07 7.16186577e-08 2.51821472e-14 2.01523722e-08
  4.61368964e-12 2.94495209e-07 1.07566744e-12 4.80223389e-06
  7.78764483e-11 4.56913358e-06 9.72359693e-12 1.15763423e-11
  4.65762469e-06 1.65073901e-13 4.28430831e-05 9.99843419e-01
  8.03611414e-11 3.16710466e-05 3.92326661e-13 1.16614392e-05
  8.89558180e-07 9.37150565e-11 2.69406537e-15 2.29240047e-11
  1.56556601e-09 1.48876234e-09 6.17232584e-11 4.02698497e-05
  1.21033577e-06 1.29512900e-05 3.35499163e-11 6.00820880e-13
  6.91335904e-16 5.44258486e-13 2.63777942e-08 3.50143200e-12
  8.83068101e-14 1.68952352e-11 6.98565511e-11 9.15063691e-10
  1.06576976e-10]]


2023-04-13 05:16:43.560619: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


In [30]:
prediction = np.argmax(prediction, axis=-1)
print(prediction[:5])

[15  4 16  9 14]


In [31]:
print(y_test[:5])

0    15
1     4
2    16
3     9
4    14
Name: prognosis, dtype: int64


In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [33]:
print(accuracy_score(y_test, prediction))

0.9761904761904762


In [34]:
print(confusion_matrix(y_test, prediction))

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
